### PR TITLE
docs(figma): obfuscate figma links under okta auth

### PR DESCRIPTION
**Pull request by dancormier**
[STACKS-608](https://stackoverflow.atlassian.net/browse/STACKS-608)

This PR obfuscate figma links under okta auth.

See also:
- https://stackexchange.slack.com/archives/C27RWNQN9/p1713382302870629
- https://stackexchange.slack.com/archives/C27RWNQN9/p1713379234110439

### To test

Checkout pages like [Color fundamentals](https://deploy-preview-1712--stacks.netlify.app/product/foundation/color-fundamentals/) or [Box Shadow](https://deploy-preview-1712--stacks.netlify.app/product/base/box-shadow/) and notice that the figma links are now forcing you to go through okta auth before being revealed.

[STACKS-608]: https://stackoverflow.atlassian.net/browse/STACKS-608?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by CGuindon — APPROVED** [review]

**Review by giamir — COMMENTED** [review]
@dancormier changes look good. Thanks.
I am happy to merge this if most people are not referring to figma via our docs.

@CGuindon @dancormier I suggested a [less drastic alternative](https://stackexchange.slack.com/archives/C27RWNQN9/p1713425676076879?thread_ts=1713382302.870629&cid=C27RWNQN9) in case we don't want to wipe all the figma badges.

**Comment by giamir** [comment]
@CGuindon can you give me a thumbs up if now the figma links make you go through the okta flow before being redirected to the actual files. Thanks

**Sidenote**
It would be nice to cleanup/organize a bit the design system figma files. In the process of mapping the redirects I noticed that there is quite a bit of inconsistencies across the files (some are even outdated I think). Shane started to clean up a bit but unfortunately he did not have the time to get very far.

**Review by giamir — APPROVED** [review]

**Review by CGuindon — CHANGES_REQUESTED** [review]
The first time I clicked the Color fundamentals Figma link, it forced me to log into okta (yay!) but after passing login, the redirect failed:
Screenshot 2024-06-04 at 8 47 13 AM

Once logged in though, if I click on the link again, it redirects correctly to Figma. If this is too tricky to fix, it's not _that big_ of a deal since you just have to click the link twice the first time.

**Comment by CGuindon** [comment]
For the sidenote: If there's a ticket in the design backlog already for this we can leave it, if not can you create one? Add any notes you have about some of the inconsistencies you saw.

**Comment by giamir** [comment]
> The first time I clicked the Color fundamentals Figma link, it forced me to log into okta (yay!) but after passing login, the redirect failed: Screenshot 2024-06-04 at 8 47 13 AM
> 
> Once logged in though, if I click on the link again, it redirects correctly to Figma. If this is too tricky to fix, it's not _that big_ of a deal since you just have to click the link twice the first time.

@CGuindon I am struggling to reproduce this somehow in my machine. 
This is the flow I consistently get. 🤔

https://github.com/StackExchange/Stacks/assets/6231616/c9dcb0e0-932e-4813-ae35-625ba2daaa9f

**Comment by CGuindon** [comment]
@giamir I was getting the error right before the Figma loading redirect screen in your flow. I just tried it again and I didn't see that error... soooo I'm tempted to say it might have been a weird edge case? Either way, still doesn't feel that big, I'll approve and if the issue comes up more often after merging we can open a new bug ticket.

**Review by CGuindon — APPROVED** [review]

**Pull request merged**
