### PR TITLE
s-code-block style tweaks

### PR DESCRIPTION
**Pull request by b-kelly**
Just a few styling tweaks for `s-code-block`:

* remove `max-height` since vertical scrolling is not desired in prod
  * re-added it for Stacks documentation *only*
* fix `s-prose` accidentally adding the inline `code` styles to our code blocks
  * docs do not exhibit this behavior because the syntax highlighting plugin (that I wrote...) adds the `s-code-block` class to *both* the `pre` and `code` elements, while prod only adds it to the `pre` element

### CODE REVIEW

**Review by aaronshekey — APPROVED** [review]
Nice catch on both of these!

**Comment by b-kelly** [comment]
Well, looks like these made their way into dev so... closing 🎉

**Comment by aaronshekey** [comment]
I still love it!

**Comment by b-kelly** [comment]
Reopened this PR because apparently I'm not firing on all cylinders today.

**Pull request merged**
