### PR TITLE
chore(border-radius): increase values by 1px; increase button, input by a step

### PR DESCRIPTION
**Pull request by PiperLawson**
Increasing border radius sizes by 1px. Increasing default border radius size from sm to md on buttons and inputs.

### CODE REVIEW

**Review by dancormier — COMMENTED** [review]
Thanks for these updates Piper. I added a commit that updates the values of border radius atomic classes and the variables that components reference, plus an update for [select](https://deploy-preview-1396--stacks.netlify.app/product/components/select/) and [input-fill](https://deploy-preview-1396--stacks.netlify.app/product/components/inputs/#input-fills) radius to match input radius.

For these components, we should only see the 1px radius increase and _not_ a step increase (like with button and input), correct?
- [avatar](https://deploy-preview-1396--stacks.netlify.app/product/components/avatars/)
- [badge](https://deploy-preview-1396--stacks.netlify.app/product/components/badges/)
- button ([badges](http://localhost:8080/product/components/buttons/#badges))
- [card](https://deploy-preview-1396--stacks.netlify.app/product/components/cards/)
- [code block](https://deploy-preview-1396--stacks.netlify.app/product/components/code-blocks/)
- [link preview](https://deploy-preview-1396--stacks.netlify.app/product/components/link-previews/)
- [notice/toast](https://deploy-preview-1396--stacks.netlify.app/product/components/notices/)
- [pagination item](https://deploy-preview-1396--stacks.netlify.app/product/components/pagination/)
- [popover](https://deploy-preview-1396--stacks.netlify.app/product/components/popovers/)
- progress ([privileges](https://deploy-preview-1396--stacks.netlify.app/product/components/progress-bars/#privileges), [badges](https://deploy-preview-1396--stacks.netlify.app/product/components/progress-bars/#badges))
- [sidebar widget](https://deploy-preview-1396--stacks.netlify.app/product/components/sidebar-widgets/)
- [tag](https://deploy-preview-1396--stacks.netlify.app/product/components/tags/)
- user card ([highlighted](https://deploy-preview-1396--stacks.netlify.app/product/components/user-cards/#highlighted))

If all of the above are only getting the 1px increase, then this should be good to go.

---

Only other question would be when can/should this be shipped in Core. If it's not intended to ship soon, I'd like to merge this only when we're ready to ship so we can easily smaller changes out in the interim.

**Comment by PiperLawson** [comment]
Can we increase toasts/notifications as well? Apologies @dancormier.

Don't need to ship now, but let's think of a way to communicate that Stacks has a change, but we want Teams/Cprod to be ready to receive first

**Comment by dancormier** [comment]
> let's think of a way to communicate that Stacks has a change, but we want Teams/Cprod to be ready to receive first

@PiperLawson do we need to communicate this to Meta explicitly when shipped or is it just Teams/Cprod? If just Teams/Cprod, can we just let them know "this change is coming to Stacks on X date" or does it need to be more of a conversation?

**Review by giamir — APPROVED** [review]
FWIW, I went through the changes and the PR looks good to me. The only open question is if we can simply cut a release and update Core when we have a chance as usual or if we need to wait up (for something ?). I would recommend to just release it as any other piece of work we do (highlighting the changelog to the product teams in the PR). @PiperLawson what are your thoughts? Can we go ahead and merge this work?

**Comment by PiperLawson** [comment]
I'm good to merge. There is also the visited link PR that I'd love to cut
with this one. When they are ready let me know and I'll find a product
developer to pull it all in

Piper Lawson
Product Designer
www.piperlawson.com

**Pull request merged**
