### PR TITLE
Use opacity only for disabled states of checkbox, radio

### PR DESCRIPTION
**Pull request by dancormier**
https://github.com/StackExchange/Stacks/issues/672

### CODE REVIEW

**Comment by dancormier** [comment]
@aaronshekey I'm assuming the linting changes are as expected. If not, yell at me.

The relevant (non-linting) changes are [`lib/css/components/_stacks-inputs.less#338`](https://github.com/StackExchange/Stacks/pull/674/files#diff-582904b8a9ccd98b678dd37d92f39bf7fecd705a1e509906842ad8051f18a1a9L338) and beyond.

**Comment by aaronshekey** [comment]
Those linting changes are definitely unexpected. Hmm. Are you running `stylelint` in Visual Studio Code? I don't think any of these should have applied, assuming our `.stylelintrc` file is working correctly. 🤔

**Comment by dancormier** [comment]
I am running stylelint in VSCode. Lemme dig a little and see what's up.

**Comment by dancormier** [comment]
Ah ha! This is the result of prettier being installed and "Format On Save" being enabled.

Closing this one. New PR incoming.

**Pull request closed without merging**
