### PR TITLE
Docs update: Add in keyboard shortcuts for search

### PR DESCRIPTION
**Pull request by hellohynes**
Small upgrade for the docs site. This PR adds some simple keyboard shortcuts for Stacks search.

- Pressing `/` focuses on the search bar
- Pressing `ESC` while focused on the search bar blurs focus

### CODE REVIEW

**Comment by aaronshekey** [comment]
Cool! This currently doesn't work on the homepage, probably because the JS just isn't included there?

**Comment by hellohynes** [comment]
Huh. The JS files were never included in the homepage layout.

**Comment by aaronshekey** [comment]
So... about that. Clicking a link in the sidebar won't work when the JS is included on the homepage, since it's trying to replace a content `div` that doesn't actually exist. We'll need to split the searching JS from the `main.js` and then include _that_ new file in both home and subpages. 😜

**Comment by hellohynes** [comment]
(╯°□°）╯┻━┻

**Pull request merged**
