### PR TITLE
Ignored post summary state

### PR DESCRIPTION
**Pull request by PiperLawson**
Updating this so I at least have one win with meta

### CODE REVIEW

**Comment by giamir** [comment]
@PiperLawson could we get some references about why we are making those changes for future references. Is there a meta post we can link to this PR? Thanks

**Comment by PiperLawson** [comment]
@giamir 
https://meta.stackexchange.com/questions/382047/my-brain-cannot-ignore-the-ignored-questions-due-to-contrast-change-please-chan/385181#385181

**Review by dancormier — CHANGES_REQUESTED** [review]
I'm hesitant to approve this PR for accessibility reasons. This [fails color contrast guidelines](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html) because the post summary can still be interacted with.

There is a way around _half_ of the issue: Most accessibility contrast checking tools check the values of the colors used. They ignore any modifications to `opacity`, so you can achieve a similar appearance just by dropping the opacity to something like `0.75`. 

## Examples

### Original

image

### Updated color values (this PR)
image


### Original w/ opacity: 0.75

image

I don't _love_ this approach for accessibility reasons, but if we have to ship this change, altering opacity would at least prevent us from failing some automated accessibility tests 🤷‍♂️

**Comment by dancormier** [comment]
superseded by https://github.com/StackExchange/Stacks/pull/1370

**Pull request closed without merging**
