### PR TITLE
High Contrast Theme: Part II

### PR DESCRIPTION
**Pull request by dancormier**
I've opened a new PR to merge into w3c/wcag#556 to 1) make sure what I'm doing makes sense before I completely blow up w3c/wcag#556 and 2) be able to easily compare and _contrast_ with deploy previews.

### CODE REVIEW

**Comment by aaronshekey** [comment]
There's something a bit gnarly about default contrast dark mode right now.

**Comment by dancormier** [comment]
> There's something a bit gnarly about default contrast dark mode right now.

Oh yeah, this is busted. Working on it.

**Comment by dancormier** [comment]
Here's a draft of some notes on this high contrast theme. Consider it a WIP.

# Why WCAG?

Some [have](https://uxmovement.com/buttons/the-myths-of-color-contrast-accessibility/) [demonstrated](https://github.com/w3c/wcag3/issues/192) that the WCAG's guidelines for contrast are far from perfect. I agree with these takes. As flawed as WCAG contrast guidelines might be, we need *some* criteria to judge contrast beyond my own vision.

Many countries have laws requiring some sector meet WCAG web accessibility guidelines or similar. Some examples (Sorry for the Western-centrism. Feel free to edit with other examples.):

- The US DOJ considers WCAG 2.0 "[the internationally recognized benchmark for web accessibility](https://www.section508.gov/blog/do-section-508-accessibility-standards-apply-to-mywebsite)"
- The Accessible Canada Act [requires WCAG 2.0 level AA compliance for Canadian websites as of January 1, 2021](https://accessible360.com/accessible360-blog/2020-02-07-accessible-canada-act/).
- While the [EU Web Accessibility Directive refers to WCAG 2.1 standards](https://siteimprove.com/en-us/accessibility/eu-web-accessibility-directive/).

If we combine WCAG guidelines with a little thoughtful judgement and feedback from [individuals that may benefit from a high contrast theme](https://makeitfable.com), I think you we can land on a theme that benefits people with vision impairments and those that just prefer a high contrast theme while satisfying enterprise customers.

# How to judge contrast

- **WCAG** (pronounced *wi kag* or *wheeeeee kag* if you're excitable)
    - [Contrast minimum](https://www.w3.org/TR/WCAG21/#contrast-minimum) 4.5:1
    - [Contrast enhanced](https://www.w3.org/TR/WCAG21/#contrast-enhanced) 7:1
    - [Non-text contrast](https://www.w3.org/TR/WCAG21/#non-text-contrast) 3:1
        - [Understanding Success Criterion 1.4.11: Non-text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html)
    - [Use of color](https://www.w3.org/TR/WCAG21/#use-of-color)
    - Exceptions to contrast requirements

        - **Incidental**: Text or images of text that are part of an inactive [user interface component](https://www.w3.org/TR/WCAG21/#dfn-user-interface-components), that are [pure decoration](https://www.w3.org/TR/WCAG21/#dfn-pure-decoration), that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement.

        - **Logotypes**: Text that is part of a logo or brand name has no contrast requirement.

        - The guidelines specify lower contrast requirements for "Large text".
- Browser dev tools
    - [Firefox Accessibility Inspector](https://developer.mozilla.org/en-US/docs/Tools/Accessibility_inspector#check_for_accessibility_issues)
        - I found the "Contrast loss" and "Achromatopsia (no color)" simulators are particularly useful
    - Firefox Add-on: [WCAG Contrast checker](https://addons.mozilla.org/en-US/firefox/addon/wcag-contrast-checker/)
    - [Chrome Lighthouse accessibility audit](https://medium.com/accessibility-a11y/do-an-accessibility-audit-using-google-chrome-lighthouse-30ff7887901c)
- Intuition and ad hoc
    - The squint test
    - Add `filter: blur(1.8px)` to `body`

## Measuring success

- Meet or exceed WCAG's Contrast minimum success criteria for all components and common uses of atomic classes
- Meet or exceed WCAG's Contrast enhanced minimum success criteria for a majority of components and uses of atomic classes
- Employ [Fable](https://makeitfable.com) (or similar) to judge

### Hard-to-quantify goals

- Keep colors distinguishable with minimal impact on contrast

# Issues

- Theme link hover/visited colors
- Popover arrow border
- Unsure if the dark, high contrast toggle component reads as a toggle (black handle dot)

## Low priority

- Progress bar backgrounds are low contrast

# General notes

- Changed selected tag background color from `--powder-400` to `--powder-300`.
    - The difference is subtle
    - It works with high contrast now

**Comment by aaronshekey** [comment]
This is really coming together, and is extremely usable so far.

Some thoughts as I poke around:

1. What if we just killed shadows in high contrast mode? They seem to muddy things up, especially in dark mode. Borders ought to be enough?
2. Do we introduce `hc:bg-black-200` and classes like it?
3. Should avatars get a border?
4. Syntax highlighting pretty much gets clobbered. Not sure what, if anything, we can do there.
5. Input focus borders need more juice. The ring itself is good, talking about the border on the element.
6. Breadcrumb dividers should be special-cased
7. The uploader needs a special case because of my "fancy" SVG border.

**Comment by dancormier** [comment]
> This is really coming together, and is extremely usable so far.
> 
> Some thoughts as I poke around:
> 
>     1. What if we just killed shadows in high contrast mode? They seem to muddy things up, especially in dark mode. Borders ought to be enough?

I kept shadows (and juiced them) because I didn't want to rely on an element having a border. Since box-shadow is can be used as an affordance to indicate grouping and stacking, I figured it was safest to just juice it and let it be ugly.

With that said, I can't find many places where it's not paired with a border. Topbar and profile avatar (though we could set conditional borders on them as needed).

I'm on the fence personally, but I'm happy to give it a go sans-shadow and see how it goes.

> 
>     2. Do we introduce `hc:bg-black-200` and classes like it?

Yep, I was thinking the same thing. I think we'll at least want monochrome `hc:bg`, and possibly `hc:fc`. Also, I think a `hc:bc-current` could be warranted.

Related to this, I'm curious to get thoughts on the bulking up of Stacks. The high contrast theme will add a bit of heft that 99% of users will never use. IMO, it's worth it but I feel kinda hazy on where the line is. Thoughts @aaronshekey ?

> 
>     3. Should avatars get a border?
> 

It's worth considering. I tended towards distinct boundaries but I also tried to not _add_ borders where they weren't previously as to not mess with layout. We could probably get away with adding a border in high contrast without screwing too much up.

>     4. Syntax highlighting pretty much gets clobbered. Not sure what, if anything, we can do 

Highlighting colors could take another look. I didn't go indepth with them and I bet there's so good prior art in highlight.js theme world to consider.

> 
>     5. Input focus borders need more juice. The ring itself is good, talking about the border on the element.

👍

> 
>     6. Breadcrumb dividers should be special-cased

👍

> 
>     7. The uploader needs a special case because of my "fancy" SVG border.

👍

**Comment by dancormier** [comment]
> 1. What if we just killed shadows in high contrast mode? They seem to muddy things up, especially in dark mode. Borders ought to be enough?

I thought about this a little more and _what if_ we change the `--bs-*` values to basically be borders? Something like:
```
    --bs-sm: 0 0 0 1px var(--black);
    --bs-md: var(--bs-sm);
    --bs-lg: var(--bs-sm);
```

Resulting in (I recommend viewing them full size):







Also, I can hear you thinking "_we gotta fix that damn popover caret_" and I agree.

> 3. Should avatars get a border?

We could also apply this to `.theme-highcontrast .s-avatar` and resolve the avatar border issue.

**Comment by aaronshekey** [comment]
Regarding shadows: In the default mode, these tend to be decorative. Those sidebar widgets become way too bold in the context of high contrast. Most elements with a shadow are paired with borders, so I think it's safe to just kill shadows in high contrast :v:

**Comment by dancormier** [comment]
Remaining issues:

> Do we introduce `hc:bg-black-200` and classes like it?

- ~~[ ] Add high contrast conditional classes as needed~~ We're gonna punt on this for now.

> Syntax highlighting pretty much gets clobbered. Not sure what, if anything, we can do 

- [ ] Investigate high contrast syntax highlighting options and implement if anything better exists.

> we gotta fix that damn popover caret

- [x] Fix popover caret shadow

---

Is this solid enough to merge into w3c/wcag#556? I figure we can address the above over there.

**Comment by Myndex** [comment]
Hello,

I am the OP of[ thread \#695 at WCAG ](https://github.com/w3c/wcag3/issues/192) which I see is referenced here. For my sins they made me an invited expert and I've been developing the new contrast methods for WCAG 3.

Two places where WCAG 2.x falls down in particular is with dark color pairs, and with inverted (light text on darker).

**APCA** is the new method for WCAG 3, and there are betas available now, including one in Chrome.

The simple standalone beta tool is https://www.myndex.com/APCA/

And the more in depth "research version" is https://www.myndex.com/SAPC/  and has some interactive experiments that demonstrate the technology.

While WCAG 3 is some time away from being an official standard, APCA can certainly provide you guidance. And I'd be eager to hear of any questions or issues along the way. I believe it can be helpful to you in developing a dark mode.

Here also are two articles that compare aspects of WCAG 2.x and APCA, and in particular answer some of the questions I saw earlier in this thread.

### [Orange You Wondering About Contrast?](https://gist.github.com/Myndex/1dadb6dcac596f1cd7a5686a076f697f#orange-you-wondering-about-contrast)

### [The Lighter Side of Dark Backgrounds](https://gist.github.com/Myndex/c30dba273aa5eca426ad9f5200917c9d#the-lighter-side-of-dark-backgrounds)

Please let me know of any questions or comments. The APCA repo is https://github.com/Myndex/SAPC-APCA  though the most current JS and constants are on the beta sites.

Thank you,


Andy


_Andrew Somers_    
_AGWG Invited Expert_    
_Myndex Color Science Researcher_     
_Inventor SAPC and APCA_      

### APCA • THE REVOLUTION WILL BE READABLE™

**Pull request merged**
