### PR TITLE
Fix #107

### LINKED ISSUE #107: On IE11, s-select menus have an extra dropdown arrow
## Steps to reproduce

Go to https://stackoverflow.design/product/components/select in IE11 and look at the dropdowns.

## Expected behavior

The dropdown has one arrow and it looks nice.

## Actual behaviour

There's an extra arrow.

According to https://stackoverflow.com/questions/20163079/remove-select-arrow-on-ie, it looks like you might just be able to add a CSS rule `.s-select select::ms-expand { display: none }`

## Screenshots

screen shot 2018-08-15 at 18 20 56

### PR DESCRIPTION
**Pull request by benjamin-hodgson**

### CODE REVIEW

**Comment by aaronshekey** [comment]
I'll give this a shot. There's a build step that needs to run if we wanna merge this in, but I can take a break and see if this works :v:

**Comment by aaronshekey** [comment]
That way you don't have to spin up all of Stacks locally.

**Comment by benjamin-hodgson** [comment]
@aaronshekey Thank you, was trying to figure out the easiest way to test this but wanted to get the PR up for review anyway cos it's such a small change

**Comment by aaronshekey** [comment]
Okie dokie. The full fix has been merged in https://github.com/StackExchange/Stacks/commit/16006a66e559514dca9bcf7d4c100115b66ac763. It'll go out in the next version bump of Stacks. Thanks for bringing this to our attention!

**Comment by benjamin-hodgson** [comment]
When are you planning to ship the version bump?

**Comment by aaronshekey** [comment]
I don't have any immediate availability to cut a new version of Stacks and get it updated on Core and Careers today, but maybe @hellohynes, @TedGoas, or @balpha could do it today? I may have some availability tomorrow.

**Comment by benjamin-hodgson** [comment]
oh ok, it can definitely wait till tomorrow. i was worried you were going to say two weeks or something

**Pull request closed without merging**
