### PR TITLE
Apply v2 colors to components proposed color alterations

### PR DESCRIPTION
**Pull request by dancormier**
This PR resolves several color contrast issues created in #1449. To compare changes visually, you can peek at these changes in [the deploy preview ](https://deploy-preview-1451--stacks.netlify.app/product/components/activity-indicator/)and compare to the [stacks-next deploy preview](https://stacks-next.stackoverflow.design/product/components/activity-indicator/).

> **Note**
> For this PR, here are the results of `npm run test:a11y` with APCA Lc 60 as of Aug 31, 2023:
>    > Chromium: |██████████████████████████████| 18/18 test files | 929 passed, 111 failed

## APCA issues

> **Note**
> Nearly all of the failures occur in dark mode. This largely seems due to the value of "white"/"black-050" in dark mode (`hsl(220, 3%, 15%)`. Changing it to `hsl(220, 3%, 8%)` resolves 62 (~40%) of the 157 issues.
> I _have not_ changed this color value in this PR.
> 
> **Update**: We have decided __not__ to change this color.

- Many theme values which were differentiated now have equivalent values. This causes issues like hover states being identical to base and/or active states. [See `lib/exports/theme.less`](https://github.com/StackExchange/Stacks/pull/1449/files#r1298480296)

### [`.has-warning`](https://deploy-preview-1451--stacks.netlify.app/product/components/inputs/#warning)
text, checkbox border too dark (I got this one as good as I could manage)

#### Before
image
image

#### After
image
image

### [**Label**](https://deploy-preview-1451--stacks.netlify.app/product/components/labels/#status)

status badges have low contrast (required, new, beta)
#### Before
image

#### After
image

### [**Activity indicator**](https://deploy-preview-1451--stacks.netlify.app/product/components/activity-indicator/#variations)

warning style too dark?

#### Before
image

#### After
image

### [**Badges**](https://deploy-preview-1451--stacks.netlify.app/product/components/badges/#badge-states)

some state badges are low contrast

#### Before
image

#### After
image

### [**Badges**](https://deploy-preview-1451--stacks.netlify.app/product/components/badges/#user-badges)

staff badge is low contrast

#### Before
image

#### After
image

### [**Banner/notice/toast**](https://deploy-preview-1451--stacks.netlify.app/product/components/banners/)

success, warning "important" banners are low contrast

#### Before
image

#### After
image

### [**Button**](https://deploy-preview-1451--stacks.netlify.app/product/components/buttons/#secondary)

base filled selected button is low contrast

> **Note**
> This PR applies what was `.s-btn__primary` styling to the `.s-btn.s-btn__filled` style and deprecates the `.s-btn__primary` variant.

#### Before
image

#### After
image

### [**Post summary**](https://deploy-preview-1451--stacks.netlify.app/product/components/post-summary/#hotness)

hotness classes are dark and difficult to differentiate

#### Before
image

#### After
image

### [**Sidebar widget**](https://deploy-preview-1451--stacks.netlify.app/product/components/sidebar-widgets/#alternative-colors)

Alt color widget headings may be too dark?

#### Before
image

#### After
image

### [**Prose**](https://deploy-preview-1451--stacks.netlify.app/product/components/prose/)

`pre` block background color possibly too pale?

**Note**: I think this is the best we're going to get, since the next color stop looks pretty dark

#### Screenshot
image

### CODE REVIEW

**Comment by PiperLawson** [comment]
**Changes to light mode**
Black-400: `210, 8, 42` (HC)

Blue-500: `210, 77, 36`
Blue-400: `210, 77, 46` (HC)

**Changes to dark mode**
Black-500: `210, 8, 90` (HC)
Black-400: `210, 8, 80` (HC)
Black-350: `210, 8, 70`
Change all blacks to have a hue of 210.

Orange-600: `27, 80, 93` (HC)
Orange-500: `27, 80, 88`
Orange-400: `27, 80, 80` (HC)

Blue-600: `210, 80, 93` (HC)
Blue-500: `210, 80, 88`
Blue-400: `210, 80, 80` (HC)

Green-600: `148, 40, 93` (HC)
Green-500: `148, 40, 85`
Green-400: `148, 40, 75` (HC)

Red-600: `0, 73, 95` (HC)
Red-500: `0, 73, 91`
Red-400: `0, 73, 85` (HC)

Yellow-600: `43, 75, 91` (HC)
Yellow-500: `43, 75, 85`
Yellow-400: `43, 75, 75` (HC)

**Comment by PiperLawson** [comment]
New color — purple (no rush!!)
This should only be used for discovery purposes (e.g., beta tag)

**Light mode**
Purple-600: `237, 50, 32`
Purple-500: `237, 50, 45`
Purple-400: `237, 55, 57`
Purple-300: `237, 60, 83`
Purple-200: `237, 77, 92`
Purple-100: `237, 80, 96`

**Dark mode**
Purple-600: `237, 65, 96`
Purple-500: `237, 60, 91`
Purple-400: `237, 58, 86`
Purple-300: `237, 32, 56`
Purple-200: `237, 27, 38`
Purple-100: `237, 25, 24`

**Comment by paintedbicycle** [comment]
First up: visual test

- The `pre` issue doesn't appear to be an issue - the new one is the same as prod, so even though it's a very light background, doesn't seem to be an issue today

- Dark mode the red activity indicator loses it's ring. I think this is low priority, just mentioning it
Screenshot 2023-08-31 at 2 36 02 PM

- Dark mode, important banner is quite ugly. No need for a fix, just mentioning it
Screenshot 2023-08-31 at 2 37 41 PM

That's really it for the visual pass (Dark mode, light mode, HC mode). Note I only focused on the screenshotted areas

Will take a look at the colour stop changes in the code next.

Thanks very much @dancormier for your attention to detail here and good choices! Many things where there is text on a background like the buttons, labels and badges look way better now

**Review by paintedbicycle — APPROVED** [review]
Thanks Dan!

**Pull request merged**
