### PR TITLE
Add an "Edit on GitHub" button

### PR DESCRIPTION
**Pull request by kylejrp**
edit-on-github

Adds an "Edit on GitHub button" to the top and bottom of the page

For those changes that you don't want to pull up an IDE for. Note that with the GitHub editor you'll have the option to commit directly or make a new branch/PR:

image

### CODE REVIEW

**Comment by aaronshekey** [comment]
Neat trick! Should we limit this to a footer on each page with the possibility of a "Last edited" date?

``` html
<div class="grid jc-space-between fc-light my48 pt24 bt bc-black-050">
    <div class="grid--cell">Last edited Friday, March 12th</div>
    <a href="https://github.com/StackExchange/Stacks/edit/develop/docs/{{ page.inputPath }}" class="grid--cell s-btn s-btn__muted">
        {% icon "Pencil" %}
        Edit on GitHub
    </a>
</div>
```

**Comment by kylejrp** [comment]
Thanks! I like just having it in the footer. I've modified my PR to include your markup. 

It has some weird vertical alignment that I'm not quite sure how to fix:
image

I'm also reading up on [Content Dates on 11ty](https://www.11ty.dev/docs/dates/) and it seems like it uses the creation date unless you manually assign dates, which might be a little tricky. 🤔 Date formatting also seems tricky. 🤷‍♂️ This is the format we get unless we add some formatting plugins (I think)
image

There's enough weirdness that I'm kinda willing to drop the date stuff for now. 😕 What do you think?

**Comment by aaronshekey** [comment]
Just pop an `ai-center` on the `grid` and it'll look great.

**Comment by aaronshekey** [comment]
> There's enough weirdness that I'm kinda willing to drop the date stuff for now.

DISAGREE :trollface:

**Comment by aaronshekey** [comment]
Oh shoot, I was too busy being a smartass to see what this would do on Netlify. Netlify builds everything from scratch so the date is actually the _build_ and not what we see locally. Hmmmmmmmmm. 🤔

**Comment by kylejrp** [comment]
Yeah, when I was testing it on my PC, all the dates were the same because I had just cloned that day. Not sure how we get dates other than manually adding it in the header of the file.

> ᵗʰᵉʳᵉ'ˢ ᵉⁿᵒᵘᵍʰ ʷᵉⁱʳᵈⁿᵉˢˢ ᵗʰᵃᵗ ⁱ'ᵐ ᵏⁱⁿᵈᵃ ʷⁱˡˡⁱⁿᵍ ᵗᵒ ᵈʳᵒᵖ ᵗʰᵉ ᵈᵃᵗᵉ ˢᵗᵘᶠᶠ ᶠᵒʳ ⁿᵒʷ

**Comment by aaronshekey** [comment]
Sorry about the back and forth. I think it belongs in the footer, but it looks a little weird without any friends down there. I can deal with it!

I've cleaned up my mess and this is ready to ~ship~ shrimp 🦐

**Review by aaronshekey — APPROVED** [review]

**Pull request merged**
