### PR TITLE
Allow s-link to be applied to button elements

### PR DESCRIPTION
**Pull request by aaronshekey**
This addresses #62.

### CODE REVIEW

**Comment by rossipedia** [comment]
umm... shouldn't that be `s-link` not `s-btn`?

**Comment by aaronshekey** [comment]
> umm... shouldn't that be s-link not s-btn?

👮

**Comment by hellohynes** [comment]
If `s-link` == `s-btn`, then what's the point of `s-link`?

**Comment by aaronshekey** [comment]
Lots of conversation in `#team-design` about this today.

We have an action that's in a banner, but the action is mutating and potentially dangerous, requiring it to be a `POST` within a form. 

image

In this case, this button needs to look and function like a link. We can make links look like buttons, so why not allow for buttons to look like links? [Bootstrap](https://getbootstrap.com/docs/4.1/components/list-group/#links-and-buttons) does this with their navigation component.

Ultimately, this is an edge case, but something Stacks didn't support.

**Pull request merged**
