### PR TITLE
Add focus/blur events to tooltips

### PR DESCRIPTION
**Pull request by dancormier**
See also: https://github.com/StackEng/StackOverflow/pull/9371

### CODE REVIEW

**Comment by aaronshekey** [comment]
Document these events as well?

**Review by b-kelly — APPROVED** [review]
lgtm! If we wanted to be fancy with it, we'd remove the hover delay for the focus event, but I'm 100% fine with this as-is.

**Comment by dancormier** [comment]
@aaronshekey I don't _think_ these need documentation. We don't really document the click events.

**Comment by aaronshekey** [comment]
> We don't really document the click events

Yep, confirmed. 🦐

**Pull request merged**
