### PR TITLE
Explore input zooming workarounds

### PR DESCRIPTION
**Pull request by aaronshekey**
This PR explores fixes for #382

### CODE REVIEW

**Comment by aaronshekey** [comment]
Using a metadata-only approach fixes the iOS use case, but disables Android's ability to pinch and zoom. Not ideal. Exploring further.

**Comment by aaronshekey** [comment]
Simply boosting the inputs to `16px` makes everything look super chunky in every context.
 
image

**Comment by bnickel** [comment]
I’m exploring something on the Ask a Question refresh project. When there’s a mouse down event I disable zooming and then reenable it a moment later. I’m nots sure how Android works so I’m currently just doing it on iOS user agents.

**Comment by bnickel** [comment]
This approach looks good on the iPhone I tested on.  Honestly, the increased font size _feels_ good on an phone.

My only notes are 1) we'll want to redo the whole `.s-input__sm` etc sizes to be relative to 16 in this case, and 2) the inputs feel very tall and we may want to adjust down the vertical padding.

**Comment by aaronshekey** [comment]
> the inputs feel very tall and we may want to adjust down the vertical padding

Good call! I'll do my best to adjust the padding to compensate for the larger font size.

**Comment by aaronshekey** [comment]
> We'll want to redo the whole `.s-input__sm` etc sizes to be relative to 16 in this case

I've explored this and found it to be very tricky considering we'll likely need to combine a responsive media query with the mobile-specific `@supports`. I can tolerate the sizing overrides not being perfect since that's an edge case that comes up way less frequently than input zooming.

**Comment by aaronshekey** [comment]
Tested on:

Windows: Internet Explorer 11, Edge, Chrome, Firefox
Mac: Safari, Chrome, Firefox
iOS 13: Safari, Chrome

**Pull request merged**
